common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from sorap import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sorap.urls')),
    path('common/', include('common.urls')),
    path('main/', views.main, name='main'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sorap/urls.py
from django.urls import path

from . import views

app_name='sorap'

urlpatterns = [
    path('', views.index,name='index'),
    path('main/',views.main,name='main'),
    path('fileupload/', views.fileUpload, name="fileupload"),
    path('filedelete/', views.fileDelete, name="filedelete"),
    path('filedownload/', views.fileDownload, name="filedownload"),

]

common/models.py
from django.db import models

# Create your models here.

sorap/models.py
from django.db import models


def user_directory_path(instance, filename):
    #this file will be uploaded to MEDIA_ROOT /user(id)/filename
    return f'user_{instance.user}/{filename}'


class FileUpload(models.Model):
    user = models.TextField(null=True)
    file_name = models.TextField(null=True)
    imgfile = models.ImageField(null=True, upload_to=user_directory_path, blank=True)

   # def __str__(self):
      #  return self.imgfile.filename()

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

sorap/forms.py
from django.forms import ModelForm
from .models import FileUpload

class FileUploadForm(ModelForm):
    class Meta:
        model = FileUpload
        fields = ['user','file_name','imgfile',]

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('main')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

sorap/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render,redirect
from .models import *
from .forms import FileUploadForm
from .models import FileUpload
from config import settings
import os
from django.http import HttpResponse


# Create your views here.
def index(request):
    return render(request, 'sorap/index.html')


def main(request):
    file_list=FileUpload.objects.filter(user=request.user.username)
    context = {'file_list': file_list}
    return render(request,'sorap/main.html',context)


def fileUpload(request):
    if request.method == 'POST':
        userinfo = request.POST["userinfo"]
        img = request.FILES["imgfile"]
        fname = img.name
        fileupload = FileUpload(
            user=userinfo,
            file_name=fname,
            imgfile=img,
        )
        fileupload.save()
        return redirect('sorap:main')
    else:
        fileuploadForm = FileUploadForm
        context = {
            'fileuploadForm': fileuploadForm,
        }
        return render(request, 'sorap/fileupload.html', context)


def fileDelete(request):
    if request.method == 'POST':
        selected = request.POST.getlist('selected')
        for item in selected:
            FileUpload.objects.filter(file_name=item).delete()
            thepath="user_"+request.user.username+"/"+item
            os.remove(os.path.join(settings.MEDIA_ROOT,thepath))
        return redirect('sorap:main')
    else:
        file_list = FileUpload.objects.filter(user=request.user.username)
        context = {'file_list': file_list}
        return render(request, 'sorap/filedelete.html', context)


def fileDownload(request):
    if request.method == 'POST':
        selected = request.POST.getlist('selected')
        for item in selected:
            thepath = "user_" + request.user.username + "/" + item
            file_path = os.path.join(settings.MEDIA_ROOT,thepath)
            binary_file = open(file_path, 'rb')
            response = HttpResponse(binary_file.read(), content_type="application/octet-stream; charset=utf-8")
            response['Content-Disposition'] = 'attachment; filename=' + os.path.basename(file_path)
            return response
        #return redirect('sorap:main')
    else:
        file_list = FileUpload.objects.filter(user=request.user.username)
        context = {'file_list': file_list}
        return render(request, 'sorap/filedownload.html', context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'sorap/style.css' %}">
    <title>Sorap Cloud System</title>
    <link rel="icon" href="/static/img/navicon.jpg">
</head>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
</body>
</html>

templates/common/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand"></a>
        {% if user.is_authenticated %}
        <img onclick="location.href='{% url 'sorap:main' %}'" src="/static/img/navicon.jpg" alt="mainicon" width="40" height="40">
        {% else %}
        <img onclick="location.href='{% url 'sorap:index' %}'" src="/static/img/navicon.jpg" alt="mainicon" width="40" height="40">
        {% endif %}
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/sorap/filedelete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if file_list %}
<div style="margin:00px 0px 00px 30px;font-size: 15px; font-family: 'Gothic';">
    <form method="POST" action="{% url 'sorap:filedelete' %}" enctype="multipart/form-data">
        {% csrf_token %}
{% for items in file_list %}
    <input type="checkbox" id="selected" name="selected" value="{{items.file_name}}">{{items.file_name}}<br>
{% endfor %}
    <input type="submit" class="btn btn-primary col" value="삭제">
    </form>
</div>
{% else %}
<div style=" padding:0px 0px 0px 4px ; margin:50px 0px 20px 0px; font-size: 18px; font-family: 'Nanum Gothic';">
<p><strong>파일이 없습니다.</strong></p>
</div>
{% endif %}
{% endblock%}

templates/sorap/filedownload.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if file_list %}
<div style="margin:00px 0px 00px 30px;font-size: 15px; font-family: 'Gothic';">
{% for items in file_list %}
    <form method="POST" action="{% url 'sorap:filedownload' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="submit" class="btn btn-primary col" value="다운로드">
    <input type="hidden" name="selected" value="{{items.file_name}}">{{items.file_name}}<br>
    </form>
{% endfor %}
</div>
{% else %}
<div style=" padding:0px 0px 0px 4px ; margin:50px 0px 20px 0px; font-size: 18px; font-family: 'Nanum Gothic';">
<p><strong>파일이 없습니다.</strong></p>
</div>
{% endif %}
{% endblock%}

templates/sorap/fileupload.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <form method="POST" action="{% url 'sorap:fileupload' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <br><br>
        <input type="hidden" name="userinfo" value="{{user.username}}">
        <p style="text-align: center;"><input type="file" data-class-button="btn btn-default" name="imgfile"><br><br><br><br>
        <input type="submit" class="btn btn-primary col" value="업로드">
        </p>
    </form>

{% endblock%}

templates/sorap/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<!DOCTYPE html>
<html>
<title>Sorap Cloud System</title>
<body>
<p style="text-align: center;">
    <img src="/static/img/mainicon.png" alt="mainicon" width="300" height="300">
</p>
<p style="text-align: center;">
    <img src="/static/img/mainletter.png" alt="mainletter" width="300" height="100">
</p>
<p style="text-align: center;">
    {% if user.is_authenticated %}
    <button type="button" class="btn text-white" style="background-color: #00FF00;" onclick="location.href='{% url 'common:logout' %}'">로그아웃</button>
    {% else %}
    <button type="button" class="btn text-white" style="background-color: #00FF00;" onclick="location.href='{% url 'common:login' %}'">로그인</button>
    {% endif %}
    <button type="button" class="btn text-white" style="background-color: #00FF00;" onclick="location.href='{% url 'common:signup' %}'">회원가입</button>
</p>
</body>
</html>

templates/sorap/main.html
{% extends "base.html" %}
{% block content %}
<br>
<div style=" padding:0px 0px 0px 4px ; margin:0px 0px 0px 10px;">
    <button type="button" class="btn text-black" style="background-color: #50FF50;" onclick="location.href='{% url 'sorap:fileupload' %}'">파일 업로드</button>
    <button type="button" class="btn text-black" style="background-color: #50FF50;" onclick="location.href='{% url 'sorap:filedelete' %}'">파일 삭제</button>
    <button type="button" class="btn text-black" style="background-color: #50FF50;" onclick="location.href='{% url 'sorap:filedownload' %}'">파일 다운로드</button>
</div>
<div style="border-bottom: solid 1px #a9a9a9; border-left: solid 7px #84C55E; padding:0px 0px 0px 4px ; margin:50px 0px 20px 0px; font-size: 18px; font-family: 'Nanum Gothic';">
<p><strong>파일함</strong></p>
</div>

{% if file_list %}
<div style="margin:00px 0px 00px 30px;font-size: 15px; font-family: 'Gothic';">
{% for items in file_list %}
    <p><a href="../filedir/user_{{user.username}}/{{items.file_name}}">{{items.file_name}}</a></p>
{% endfor %}
</div>
{% else %}
<div style=" padding:0px 0px 0px 4px ; margin:50px 0px 20px 0px; font-size: 18px; font-family: 'Nanum Gothic';">
<p><strong>파일이 없습니다.</strong></p>
</div>
{% endif %}
{% endblock %}